export { default as CLayout } from './layout.vue'
export { default as CHeader } from './header.vue'
export { default as CAside } from './aside.vue'
export { default as CMain } from './main.vue'
export { default as CFooter } from './footer.vue'
